/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-102947-g7bd7377ddb-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
